### PR TITLE
Update metadata to include Python 3.11

### PR DESCRIPTION
**Pull request by bdpedigo**

### CODE REVIEW

**Comment by bdpedigo** [comment]
I don't see anything in https://github.com/bdpedigo/graspologic-native/blob/patch-1/.github/workflows/build.yml that looks like it needs to change?

**Comment by bdpedigo** [comment]
@daxpryce I think something like this would be required to get graspologic on Python 3.11, let me know your thoughts

**Comment by daxpryce** [comment]
I think this is right.  At the least we can publish a pre-release and then try it locally with a graspologic before pushing to main.

**Comment by daxpryce** [comment]
Let's see how it goes once the action runners build the build for it :)

**Comment by bdpedigo** [comment]
> Let's see how it goes once the action runners build the build for it :)

i think all done and successful!

**Review by daxpryce — APPROVED** [review]

**Comment by bdpedigo** [comment]
> I think this is right. At the least we can publish a pre-release and then try it locally with a graspologic before pushing to main.

not actually sure how this went up as a non-prerelease... 🤔  https://pypi.org/project/graspologic-native/1.2.0/#history

**Comment by daxpryce** [comment]
I'm not sure either; if you look at the artifacts generated by the run, version.txt, Cargo.toml both have the prerelease version, but it seems like the maturin action just didn't give a crap and decided it was a final release?  Because of course it did; why wouldn't it have.

**Pull request merged**
